### ISSUE TITLE
使用方法咨询

### ISSUE THREAD

**Issue by MaleicAcid** [traj-explorer/glink#4]
glink的作者你们好, 我需要用flink做一个地理位置相关的业务工作，很高兴搜到了你们这个库, 但发现还没有使用文档，我想请问一下目前这个库能支持查询某个点是否在一个多边形区域里吗？
我的业务场景为: 读取许多艘船的运动轨迹流, 对它们1分钟后的轨迹进行预测, 对过近的船计算他们的“预警”指标
1. 从数据源读取许多艘船的运动轨迹流(ship1的轨迹，ship2的轨迹...)
2. 把流按船舶编号划分, 并预测生成各个船的流(ship1_1分钟后的轨迹), (ship2_1分钟后的轨迹)...(shipN_1分钟后的轨迹)
3. 查询预测出的未来同一时刻下(比如20s时, 40s时, 在某个多边形(或圆形)范围内的船, 并根据船自身参数计算两艘船的“预警”指标

我目前还是一个学习flink不久的新手, 请问这样的一个功能可以使用你们的库来实现吗? 
如果您愿意给我一些思路上的建议, 我将万分感激 ;)

**Comment by LB-Yu** [comment]
非常抱歉，glink的定位是一个通用的时空流数据处理平台，目前恐怕无法直接支持您所描述的业务场景，对于轨迹数据的处理是后续我们会考虑的重点。但是我们很乐意为您的场景提供一些解决思路（不一定唯一）。从您的描述中我想可以对您的需求做如下转化：
1. 对轨迹源流进行预测，形成预测流，这可能可以通过一个简单的map函数实现，取决于您的预测算法，如果需要用到更多的历史数据可以使用state保存；
2. 通过一个窗口函数计算落在指定多边形内的轨迹点。
